default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: henokkh
  password: 123456
  pool: 5

development:
  <<: *default
  database: rails_random_greeting_dev

test:
  <<: *default
  database: rails_random_greeting_test

production:
  <<: *default
  database: rails_random_greeting_prod
  username: <%= ENV["PROD_DB_USER"] %>
  password: <%= ENV["PROD_DB_PASSWORD"] %>
